# Generated by Django 3.1.3 on 2020-11-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interviewees',
            fields=[
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('phoneNo', models.CharField(max_length=200)),
                ('resumeLink', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Interviewers',
            fields=[
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('phoneNo', models.CharField(max_length=200)),
            ],
        ),
    ]
