# Generated by Django 3.1.3 on 2020-11-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20201109_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(max_length=200)),
                ('resume', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
    ]
