# Generated by Django 3.1.3 on 2020-11-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_test2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resumes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervieweeEmail', models.CharField(max_length=200)),
                ('intervieweeResume', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
        migrations.AlterField(
            model_name='interviewees',
            name='resumeLink',
            field=models.CharField(max_length=1000),
        ),
    ]
